### ISSUE TITLE
Example for how to `go` in function

### ISSUE THREAD

**Issue by Hongbo-Miao** [brunnolou/react-morph#4]
An example for how to `go` in function will be great. Thanks for the cool package!

```js
handleGo = () => {
  // ...
}

<ReactMorph>
  {({ from, to, fadeIn, go }) => (
    <div>
      <a onClick={this.handleGo}>
        <strong {...from("title")}>ReactMorph 🐛</strong>
        <br />
        <p {...from("description")}>Morphing transitions was never so easy!</p>
      </a>

      <div>
        <h1 {...to("title")}>ReactMorph 🦋</h1>
        <br />
        <h2 {...to("description")}>Morphing transitions was never so easy!</h2>

        <a onClick={() => go(0)} {...fadeIn()}>
          Back
        </a>
      </div>
    </div>
  )}
</ReactMorph>
```

**Comment by beepcode** [comment]
Seems to be added to the readme already: 

`<a onClick={() => go(1)}>`

**Comment by Hongbo-Miao** [comment]
Hi @beepcode, sorry for not clear. I mean using in user’s own function like the handleGo in the above code.

**Comment by beepcode** [comment]
Ok, the simplest solution would be to pass the go() function as a parameter. This would look like so:

`handleGo = (go) => {
  go();
}`

...

`<a onClick={() => this.handleGo(go)}>
 `

**Comment by Hongbo-Miao** [comment]
Thanks, @beepcode , that is what I thought.

But `() => this.handleGo(go)` will causing rerender, right?

If it is, maybe export something like below

```
import { morphGo } from "react-morph";

handleGo = () => {
  morphGo();
  // something else
}
```
will help?

**Comment by beepcode** [comment]
You could use the lifecycle method "shouldComponentUpdate()" to prevent rerender.

**Comment by Hongbo-Miao** [comment]
Thanks, I get it.
Hope the package can handle those things. Better experience for the rest of people.

**Comment by beepcode** [comment]
What are you trying to achieve exactly? Which "business case" are you trying to find a solution to? From my perspective the sole purpose of "go()" is to start the morph, so rerender is expected. Or are you trying to trigger the morph from outside?

**Comment by Hongbo-Miao** [comment]
Oh, you are right! I forget rerender is necessary in this case for the animation. My bad.
